### ISSUE TITLE
feature: "stable clone" of repositories for the omnipath

### ISSUE THREAD

**Issue by XaF** [XaF/omni#16]
If working regularly on a repository, the omnipath updates will often fail to update the repository as it's not checked out on the expected branch. Most of the time this is desirable, as it allows people to dynamically work on building a command. But in other cases, this forces to manually update the repository to have the latest commands from it.

Wondering what could be a good interface:
- special flag at clone time to clone a repo "in path mode", in a separate directory, which would make that repo not a "work repo" but a "path repo" that the user does not touch ?
- command to create a "path mode" repository from the current repository ?
- command to create a "path mode" __worktree__ from the current repository ? (would be an issue when updating repositories by tag though)

**Comment by XaF** [comment]
@dynajoe suggested a `package` approach, which I believe could work for this.

As a refined idea, a package can be referred to as:

```
path:
  append:
    - package: git@github.com:XaF/omni  # defaults to `cmd` subdir ? or `omni` subdir ?
    - package: git@github.com:XaF/omni
      dir: cmd2
    - /Users/xaf/...
    - path: /Users/xaf/...
```

When using a `package` in the path, the repository will be cloned into an omni data directory (along `asdf`), and that path will be used as the omnipath. This will allow making sure that the local development versions of the users are not affecting omni's behavior.

On top of that, we will also want to:
- support suggesting cloning repositories `as a package` when going through `suggest_clone` (do you want to clone xxx as a package ?)
- detect when a `omni up`-ed repository is a package, and adapt the relative-path-to-absolute-path feature to keep the configuration into package setup (e.g. `path: relpath` would become `path: { package: xxx, dir: relpath }` instead of `path: abspath`
