### ISSUE TITLE
Add support for configuration for the init hook

### ISSUE THREAD

**Issue by XaF** [XaF/omni#195]
The init hook now takes `--alias` and `--command-alias` parameters.
It would be useful to provide support to set that configuration through a configuration file too. Something like `init.yaml`, `shell.yaml` or even `aliases.yaml` could work. **Maybe it could simply be part of the default configuration file?**

The file could for now contain:
```yaml
shell_aliases:
  - alias: o              # Provides an alias to `omni`
  - alias: ocd            # Provides an alias to `omni cd`
    target: cd
  - alias: whatever       # Provides an alias to `omni whatever`
    target: whatever
```
