### ISSUE TITLE
Feature: support for `suggest_clone` in repositories' omni configuration

### ISSUE THREAD

**Issue by XaF** [XaF/omni#21]
A repository can specify configuration, but could also suggest repositories to clone, which would trigger a prompt asking the user which repositories they want to clone.

Something like:

```yaml
suggest_clone:
  - git@github.com:XaF/omni
  - git@github.com:omnicli/omni-example
```

We could also support a `if` parameter to conditionnally suggest repositories:

```yaml
suggest_clone:
  - git@github.com:XaF/omni1
  - if: <bash -c code>
    then:
      - git@github.com:XaF/omni2
    else:
      - git@github.com:omnicli/omni-example
```
