### ISSUE TITLE
`python` up operation should also handle `pip` requirements

### ISSUE THREAD

**Issue by XaF** [XaF/omni#279]
This could look like:

```yaml
up:
  - python:
      version: 3
      pip: path/to/requirements.txt
```

or

```yaml
up:
  - python:
      version: 3
      dir: some/path/to/apply
      pip: path/to/requirements.txt
```

or

```yaml
up:
  - python:
      version: 3
      pip:
        - path/to/requirements.txt
```

or

```yaml
up:
  - python:
      version: auto
      pip:
        - path/to/requirements.txt
        - other/path/to/requirements.txt
```

With that latest, each requirements file would be applied to the python version locale to the repository it is. If a requirements file is out of any repository with a python version for that directory, the operation should fail.
