### ISSUE TITLE
Ability to set PYTHONPATH

### ISSUE THREAD

**Issue by njo** [XaF/omni#358]
My omni scripts live in `/scripts/`

but my python library code lives in:
`/project/python/`

Right now I have to hack `sys.path` in my scripts to load the library in `project/python/` but it'd be great to provide a way to add arbitrary paths when running python scripts. Either with the `PYTHONPATH` env or just modify the `PATH`.

https://omnicli.dev/reference/configuration/parameters/up/python#dynamic-environment

**Comment by XaF** [comment]
This will be handled by the `env` parameter in 0.0.20.
Something like the following should allow that:

```yaml
env:
  PYTHONPATH:
    prepend:
      value: project/python
      type: path
```
