### ISSUE TITLE
`github-release`: support specifying a token in the configuration

### ISSUE THREAD

**Issue by XaF** [XaF/omni#512]
Follow-up to: https://github.com/XaF/omni/issues/478

For cases where `gh` is not available, we should support to set a PAT in the configuration.

```yaml
# Using gh auth token
github:

# Using gh auth token
github:
  auth:
    gh:

# Using gh auth token --hostname xxx
github:
  auth:
    gh:
      hostname: xxx

# Using gh auth token --hostname xxx --user yyy
github:
  auth:
    gh:
      hostname: xxx
      user: yyy

# Using TTT as token
github:
  auth:
    token: TTT
```
