### ISSUE TITLE
env parameter in config inserts `.omni.yaml` into the path when using absolute paths

### ISSUE THREAD

**Issue by florzanetta** [XaF/omni#564]
After adding the excerpt below to my repo's config and running `omni up`, the path wasn't resolved properly.

```yaml
env:
  PYTHONPATH:
    prepend:
      value: path/to/my/lib
      type: path
```

`print(os.environ["PYTHONPATH"])` produced `/path/to/repo/.omni.yaml/path/to/my/lib`
