### ISSUE TITLE
`up`: add support to `cargo install` binaries similarly to the `go-install` operation

### ISSUE THREAD

**Issue by XaF** [XaF/omni#798]
Similar to https://github.com/XaF/omni/issues/714 and its implementation in https://github.com/XaF/omni/issues/797, we should have support for `cargo install` operations.

```yaml
up:
  - cargo-install:
    - riggrep: 0.1.16
```
